(() => {
"use strict";
const QUESTIONS=[{"name":"Maya","title":"A first year at a two-year college","program":2,"expenses":[["Tuition and fees",4200],["Books and supplies",800],["Transportation",1000],["Personal expenses",600]],"target":1,"parent":{"amount":2400},"award":0,"saved":600,"time":18,"unit":"months","mode":"drop"},{"name":"Andre","title":"Save for the first two years","program":4,"expenses":[["Tuition and fees",8800],["Housing and meals",6400],["Books and supplies",1000],["Transportation",800]],"target":2,"parent":{"amount":12000},"award":4000,"saved":2000,"time":4,"unit":"years","mode":"drop"},{"name":"Leah","title":"Parents contribute a percent","program":4,"expenses":[["Tuition and fees",12000],["Housing and meals",8000],["Books and supplies",1200],["Transportation",800]],"target":1,"parent":{"percent":60},"award":1800,"saved":1000,"time":2,"unit":"years","mode":"mc"},{"name":"Noah","title":"Two years with family help","program":2,"expenses":[["Tuition and fees",4800],["Books and supplies",900],["Transportation",1300],["Personal expenses",1000]],"target":2,"parent":{"percent":75},"award":0,"saved":800,"time":20,"unit":"months","mode":"mc"},{"name":"Elena","title":"A minimum monthly savings plan","program":4,"expenses":[["Tuition and fees",9600],["Housing and meals",7200],["Books and supplies",1200],["Transportation",1000]],"target":1,"parent":{"amount":7500},"award":1500,"saved":1600,"time":3,"unit":"years","mode":"mc"},{"name":"Nia","title":"Plan independently for two years","program":2,"expenses":[["Tuition and fees",5000],["Books and supplies",900],["Transportation",1100],["Personal expenses",1000]],"target":2,"parent":{"percent":50},"award":0,"saved":2000,"time":30,"unit":"months","mode":"drop"},{"name":"Owen","title":"Plan with and without a scholarship","program":4,"expenses":[["Tuition and fees",10000],["Housing and meals",6000],["Books and supplies",1000],["Transportation",1000]],"target":1,"parent":{"amount":5000},"award":2400,"uncertain":true,"saved":1000,"time":24,"unit":"months","mode":"drop"},{"name":"Zoe","title":"A family percentage and a scholarship","program":4,"expenses":[["Tuition and fees",11000],["Housing and meals",7000],["Books and supplies",1400],["Transportation",600]],"target":2,"parent":{"percent":65},"award":3000,"saved":2600,"time":5,"unit":"years","mode":"mc"},{"name":"Devin","title":"First-year savings at a two-year college","program":2,"expenses":[["Tuition and fees",3600],["Books and supplies",800],["Transportation",1200],["Personal expenses",400]],"target":1,"parent":{"amount":2400},"award":0,"saved":900,"time":18,"unit":"months","mode":"mc"},{"name":"Imani","title":"Fund the first two years of a four-year college","program":4,"expenses":[["Tuition and fees",13500],["Housing and meals",8500],["Books and supplies",1200],["Transportation",800]],"target":2,"parent":{"percent":40},"award":4800,"saved":3600,"time":4,"unit":"years","mode":"mc"}];
const STEPS=["Add college expenses","Calculate family help","Find the student's share","Count saving months","Plan monthly savings"];
const money=c=>"$"+(c/100).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=v=>String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");
function totals(q,withAward=true){const annual=q.expenses.reduce((s,e)=>s+e[1]*100,0),program=annual*q.program,target=annual*q.target,parent=q.parent.percent!==undefined?Math.round(target*q.parent.percent/100):q.parent.amount*100,award=withAward?q.award*100:0,share=target-parent-award,remaining=share-q.saved*100,months=q.unit==="years"?q.time*12:q.time;return {annual,program,target,parent,award,share,remaining,months,monthly:Math.ceil(remaining/months)};}
function reset(data,index){Object.assign(data,{index,step:0,answers:{},selected:null,verified:false,answered:false});}
function options(correct,alternatives,seed){const values=[...new Set([correct,...alternatives.filter(v=>Number.isInteger(v)&&v>=0)])];for(let n=1;values.length<4;n++)if(!values.includes(correct+100*n))values.push(correct+100*n);const result=values.slice(0,4);for(let n=0;n<seed%4;n++)result.push(result.shift());return result;}
function expenseTable(q){return '<div class="g812-table-wrap"><table><caption>Estimated expenses for one year at a '+q.program+'-year college</caption><thead><tr><th scope="col">Expense</th><th scope="col">Annual cost</th></tr></thead><tbody>'+q.expenses.map(e=>'<tr><th scope="row">'+esc(e[0])+'</th><td>'+money(e[1]*100)+'</td></tr>').join("")+'</tbody></table></div>';}
function story(q){const period=q.target===1?"the first year":"the first two years";return '<article class="g812-story"><h5>Read the problem</h5><p>'+q.name+' plans to attend a '+q.program+'-year college and wants to have enough money before starting college to cover <strong>'+period+'</strong>. The table lists all estimated annual expenses.</p>'+expenseTable(q)+'<ul><li>'+q.name+"'s parents will contribute "+(q.parent.percent!==undefined?'<strong>'+q.parent.percent+'% of the total expenses for '+period+'</strong>':'<strong>'+money(q.parent.amount*100)+'</strong> in total for '+period)+'.</li>'+(q.award?'<li>'+q.name+(q.uncertain?' has applied for a scholarship of <strong>'+money(q.award*100)+'</strong>, but it has not been awarded.':' has been awarded a scholarship of <strong>'+money(q.award*100)+'</strong> in total for '+period+'.')+'</li>':'')+'<li>'+q.name+' already has <strong>'+money(q.saved*100)+'</strong> saved toward the student’s share.</li><li>'+q.name+' will save the same amount each month for the next <strong>'+q.time+' '+q.unit+'</strong> before college.</li></ul><p class="g812-note">Assume the annual expenses stay the same, savings earn no interest, and no other contributions are made. Parent and scholarship contributions are separate from the student’s existing savings.</p></article>';}
function targets(q,r,step){if(step===0)return [{key:"annual",label:"Total expenses for one year",value:r.annual},{key:"program",label:"Estimated cost of the full "+q.program+"-year education",value:r.program},{key:"target",label:"Cost to fund "+(q.target===1?"the first year":"the first two years"),value:r.target}];if(step===1)return [{key:"parent",label:"Parents' contribution",value:r.parent}];if(step===2)return [{key:"share",label:"Student's total contribution",value:r.share},{key:"remaining",label:"Additional money the student must save",value:r.remaining}];if(step===3)return [{key:"months",label:"Number of months to save",value:r.months,number:true}];return [{key:"monthly",label:"Minimum amount to save each month",value:r.monthly}];}
function bank(q,r,items,seed){let alternatives=[r.annual,r.target,r.program,r.parent,r.share,r.remaining,r.monthly,q.saved*100,r.award,Math.ceil(r.target/r.months),Math.ceil(r.share/r.months)];if(items[0].number)alternatives=[q.time,r.months+12,r.months/2,q.time*12];const answerValues=items.map(t=>t.value),distractors=alternatives.filter(n=>Number.isInteger(n)&&n>=0&&!answerValues.includes(n)),arr=[...new Set([...answerValues,...distractors.slice(0,3)])];for(let i=0;i<seed%arr.length;i++)arr.push(arr.shift());return arr;}
function dropContent(data,items,bankValues){const number=items[0].number;return '<div class="g812-bank" aria-label="Answer bank">'+bankValues.map(value=>'<button type="button" draggable="true" data-g812-chip="'+value+'" class="g812-chip'+(data.selected===value?' selected':'')+'" aria-pressed="'+(data.selected===value)+'" '+(data.verified?'disabled':'')+'>'+ (number?value+" months":money(value))+'</button>').join("")+'</div><p class="g812-note">Drag an answer into each box, or select an answer and then select its box. Answers may be used more than once. Some answers will not be used. Double-click a box to clear it.</p><div class="g812-slots">'+items.map(t=>'<button type="button" data-g812-slot="'+t.key+'" class="g812-slot" '+(data.verified?'disabled':'')+' aria-label="'+esc(t.label)+'"><small>'+esc(t.label)+'</small><strong>'+(data.answers[t.key]!==undefined?(t.number?data.answers[t.key]+" months":money(Number(data.answers[t.key]))):"Drop answer")+'</strong></button>').join("")+'</div>';}
function choiceText(items,values){return items.map((t,i)=>t.label+': '+(t.number?values[i]+" months":money(values[i]))).join(" · ");}
function mcChoices(q,r,items,seed){const actual=items.map(t=>t.value);let choices=[{key:"correct",text:choiceText(items,actual)}];if(items.length===3){choices.push({key:"a",text:choiceText(items,[r.annual,r.annual,r.annual])},{key:"b",text:choiceText(items,[r.annual,r.program,r.program])},{key:"c",text:choiceText(items,[r.annual+q.expenses[0][1]*100,r.program,r.target])});}else if(items.length===2){choices.push({key:"a",text:choiceText(items,[r.target,r.target-q.saved*100])},{key:"b",text:choiceText(items,[r.target-r.parent,r.target-r.parent-q.saved*100])},{key:"c",text:choiceText(items,[r.remaining,r.share])});}else{const value=actual[0];let alternatives=items[0].number?[q.time,r.months+12,r.months/2]:items[0].key==="parent"?[r.target-r.parent,r.annual,Math.round(r.target*(q.parent.percent||100)/10000)]:[Math.ceil(r.share/r.months),Math.ceil(r.target/r.months),Math.ceil(r.remaining/q.time)];choices=options(value,alternatives,0).map(v=>({key:v===value?"correct":"value"+v,text:choiceText(items,[v])}));}const unique=[];for(const c of choices)if(!unique.some(x=>x.text===c.text))unique.push(c);for(let i=1;unique.length<4;i++)unique.push({key:"fallback"+i,text:choiceText(items,actual.map(v=>v+i*100))});const arr=unique.slice(0,4);for(let i=0;i<seed%4;i++)arr.push(arr.shift());return arr;}
function mcContent(data,choices){return '<div class="g812-choices" role="group" aria-label="Answer choices">'+choices.map((c,i)=>'<button type="button" class="g812-choice'+(data.answers.mc===c.key?' selected':'')+'" data-g812-mc="'+c.key+'" aria-pressed="'+(data.answers.mc===c.key)+'" '+(data.verified?'disabled':'')+'><b>'+String.fromCharCode(65+i)+'</b><span>'+esc(c.text)+'</span></button>').join("")+'</div>';}
function instruction(q,r,step){if(step===0)return "Add all annual expenses. Use that annual total to estimate the full "+q.program+"-year education cost and the cost for the "+(q.target===1?"first year":"first two years")+" that the student wants to fund.";if(step===1)return q.parent.percent!==undefined?"Divide the parents' percent by 100, then multiply by the verified cost for the period being funded.":"Identify the total amount the parents will contribute for the period being funded.";if(step===2)return "Subtract the parents' contribution and any awarded scholarship from the cost being funded. This is the student's total contribution. Then subtract the student's existing savings to find the additional money to save.";if(step===3)return q.unit==="years"?"Multiply the number of saving years by 12 to find the number of months.":"The saving time is already given in months. Use that number of monthly deposits.";return "Divide the additional money needed by the number of saving months. If the result has more than two decimal places, round UP to the next cent so the savings will be enough.";}
function recap(q,r,step){let lines=[];if(step>0)lines.push("One year: "+money(r.annual)+"; full "+q.program+"-year education: "+money(r.program)+"; cost being funded: "+money(r.target)+".");if(step>1)lines.push("Parents: "+money(r.parent)+(r.award?"; awarded scholarship: "+money(r.award):"")+".");if(step>2)lines.push("Student's total contribution: "+money(r.share)+"; additional money to save: "+money(r.remaining)+".");if(step>3)lines.push("Saving time: "+r.months+" months.");return lines.length?'<div class="g812-recap"><strong>Verified work</strong>'+lines.map(l=>'<p>'+esc(l)+'</p>').join("")+'</div>':"";}
function worked(q){const r=totals(q);let html='<article class="g812-explanation"><h5>Check the savings plan</h5><p>Annual expenses: '+q.expenses.map(e=>money(e[1]*100)).join(" + ")+' = <strong>'+money(r.annual)+'</strong>.</p><p>Full '+q.program+'-year education estimate: '+money(r.annual)+' × '+q.program+' = '+money(r.program)+'. Cost being funded: '+money(r.annual)+' × '+q.target+' = <strong>'+money(r.target)+'</strong>.</p><p>Parents contribute '+(q.parent.percent!==undefined?q.parent.percent+'% ÷ 100 = '+q.parent.percent/100+'; '+money(r.target)+' × '+q.parent.percent/100+' = ':'')+'<strong>'+money(r.parent)+'</strong>.</p>';const plan=(rr,label)=>'<p><strong>'+label+'</strong> Student’s total contribution: '+money(rr.target)+' − '+money(rr.parent)+' − '+money(rr.award)+' = '+money(rr.share)+'. Subtract existing savings: '+money(rr.share)+' − '+money(q.saved*100)+' = '+money(rr.remaining)+'.</p><p>'+money(rr.remaining)+' ÷ '+rr.months+' months = <strong>'+money(rr.monthly)+' per month</strong>'+ (rr.remaining%rr.months?'; rounded up to the next cent so the goal is met':'')+'.</p>';html+=q.uncertain?plan(r,"If the scholarship is awarded:")+plan(totals(q,false),"If the scholarship is not awarded:"):plan(r,"Savings plan:");return html+'<p>The college years being funded and the years available to save are different quantities.</p></article>';}
window.COLLEGE_812G_TOTAL=QUESTIONS.length;
window.reset812GQuestion=reset;
window.render812GLab=function(ctx){
const {labRuntime,$,setLabProgress,setLabFeedback,showLabCompletion,syncWhiteboardQuestion}=ctx;
const data=labRuntime.data||(labRuntime.data={index:0,step:0,answers:{},selected:null,verified:false,answered:false}),q=QUESTIONS[data.index],r=totals(q),guided=data.index<5,body=$("#standardsLabBody"),render=()=>window.render812GLab(ctx);
setLabProgress(data.index+(data.answered?1:0),QUESTIONS.length,guided?"Question "+(data.index+1)+": step "+(data.step+1)+" of 5.":"Build the savings plan independently.");
let items,choices=null,content="";
if(guided){items=targets(q,r,data.step);content='<ol class="g812-steps">'+STEPS.map((name,i)=>'<li class="'+(i===data.step?'active':i<data.step?'done':'')+'" '+(i===data.step?'aria-current="step"':'')+'><b>'+(i<data.step?'✓':i+1)+'</b><span>'+name+'</span></li>').join("")+'</ol>'+recap(q,r,data.step)+'<h5>Step '+(data.step+1)+': '+STEPS[data.step]+'</h5><p>'+instruction(q,r,data.step)+'</p>';
}else{items=q.uncertain?[{key:"with",label:"Monthly savings if the scholarship is awarded",value:r.monthly},{key:"without",label:"Monthly savings if the scholarship is not awarded",value:totals(q,false).monthly}]:q.mode==="drop"?[{key:"share",label:"Student's total contribution before using existing savings",value:r.share},{key:"monthly",label:"Minimum amount to save each month",value:r.monthly}]:[{key:"monthly",label:"Minimum amount to save each month",value:r.monthly}];content='<h5>'+(q.uncertain?"Complete both savings plans.":q.mode==="drop"?"Find the student's total contribution and monthly savings.":"What is the minimum amount the student should save each month?")+'</h5><p class="g812-note">If needed, round UP to the next cent so the savings cover the required amount.</p>';}
const values=bank(q,r,items,data.index+data.step);
if(q.mode==="drop")content+=dropContent(data,items,values);else{choices=mcChoices(q,r,items,data.index+data.step);content+=mcContent(data,choices);}
content+='<button type="button" id="g812Check" class="lab-action" '+(data.verified?'disabled':'')+'>'+ (guided?"Check this step":"Check answer")+'</button>'+(guided&&data.verified&&!data.answered?'<button type="button" id="g812Step" class="lab-next">Next step →</button>':'');
body.innerHTML='<section class="g812-lab"><header><p>8.12G · QUESTION '+(data.index+1)+' OF 10 · '+(guided?'GUIDED PRACTICE':'INDEPENDENT PRACTICE')+'</p><h4>'+esc(q.title)+'</h4></header>'+story(q)+content+(data.answered?worked(q)+'<button type="button" id="g812Next" class="lab-next">'+(data.index===9?"Finish lab":"Next question →")+'</button>':'')+'</section>';
body.querySelectorAll("[data-g812-mc]").forEach(button=>button.addEventListener("click",()=>{if(data.verified)return;data.answers.mc=button.dataset.g812Mc;setLabFeedback("");render();}));
body.querySelectorAll("[data-g812-chip]").forEach(button=>{const value=Number(button.dataset.g812Chip);button.addEventListener("click",()=>{if(data.verified)return;data.selected=value;body.querySelectorAll("[data-g812-chip]").forEach(el=>{el.classList.toggle("selected",Number(el.dataset.g812Chip)===value);el.setAttribute("aria-pressed",String(Number(el.dataset.g812Chip)===value));});setLabFeedback("Answer selected. Choose a box.");});button.addEventListener("dragstart",event=>{if(data.verified){event.preventDefault();return;}data.selected=value;event.dataTransfer.setData("text/plain",String(value));event.dataTransfer.effectAllowed="copy";});});
body.querySelectorAll("[data-g812-slot]").forEach(button=>{const place=value=>{if(data.verified||value===null||!values.includes(value))return;data.answers[button.dataset.g812Slot]=value;data.selected=null;setLabFeedback("");render();};button.addEventListener("click",()=>place(data.selected));button.addEventListener("dragover",event=>{if(!data.verified){event.preventDefault();event.dataTransfer.dropEffect="copy";}});button.addEventListener("drop",event=>{event.preventDefault();const text=event.dataTransfer.getData("text/plain");if(text.trim()!=="")place(Number(text));});button.addEventListener("dblclick",()=>{if(data.verified)return;delete data.answers[button.dataset.g812Slot];data.selected=null;setLabFeedback("");render();});});
$("#g812Check").addEventListener("click",()=>{if(data.verified)return;const correct=q.mode==="mc"?data.answers.mc==="correct":items.every(t=>data.answers[t.key]===t.value);if(!correct)return setLabFeedback(guided?"Try again. "+instruction(q,r,data.step):"Recheck the expenses for the requested college years, the contributions and existing savings, and the months available to save.","incorrect");data.verified=true;if(!guided||data.step===4)data.answered=true;render();setLabFeedback(data.answered?"Correct. Review the savings plan below.":"Correct. Continue to the next step.","correct");});
const nextStep=$("#g812Step");if(nextStep)nextStep.addEventListener("click",()=>{if(!data.verified)return;data.step++;data.answers={};data.selected=null;data.verified=false;setLabFeedback("");render();syncWhiteboardQuestion();});
const next=$("#g812Next");if(next)next.addEventListener("click",()=>{if(!data.answered)return;if(data.index===9)return showLabCompletion("8.12G");reset(data,data.index+1);setLabFeedback("");render();syncWhiteboardQuestion();});
};
})();
