import {livePage} from './live-page.mjs';
export function dashboardPage(){
 let html=livePage().replace('<title>Math Help Live • 8th Grade Math Word Wall</title>','<title>Owner Dashboard • Your Digital Learning Wall</title>');
 const start=html.indexOf('<main>'), bodyEnd=html.indexOf('</main>');
 let content=html.slice(start+6,bodyEnd);
 content=content.slice(content.indexOf('<div class="panel">'));
 content=content.replace('<h2>Request private tutoring</h2>','<h2 id="tutoring-heading">Tutoring &amp; appointments</h2>').replace('<p>Request a daytime or evening hour at least 48 hours ahead. The instructor will approve a time before you pay. Payment is separate from website access.</p>','<p>Review requests, approve a suitable hour, and add private lesson links after payment.</p>');
 content=content.replace('<h2>Instructor controls</h2>','<h2>Live lesson &amp; learner access</h2>');
 const shell=`<div class="dashboard-layout"><aside class="sidebar"><a class="brand" href="/dashboard"><img src="/brand-logo.svg" alt="Myelinated Melanin logo"><span>Your Digital<br>Learning Wall<small>OWNER WORKSPACE</small></span></a><nav><a href="#overview">Overview</a><a href="#memberships">Memberships &amp; learners</a><a href="#questions">Question queue</a><a href="#requests">Tutoring requests</a><a href="#live-settings">Live lesson</a><a href="#complimentary-form">Complimentary access</a></nav><small>YOUR LEARNING SPACE</small><nav><a href="/">Open word wall ↗</a><a href="/live">View learner page ↗</a></nav></aside><main class="dashboard-main"><div class="dash-top"><span class="eyebrow">YOUR DIGITAL LEARNING WALL / DASHBOARD</span><div id="dashboard-user"></div></div><section id="overview" class="welcome"><p class="eyebrow">OWNER WORKSPACE</p><h1>Your work. Their next breakthrough.</h1><p>Welcome back, Karista. Bring your learners, lessons, and requests together in one place.</p><a class="button" href="#requests">Review tutoring requests</a></section><div class="metrics"><div class="metric"><b id="metric-members">—</b><span>Active paid / trial accounts</span></div><div class="metric"><b id="metric-learners">—</b><span>Class enrollments</span></div><div class="metric"><b id="metric-requests">—</b><span>Tutoring requests awaiting review</span></div><div class="metric"><b id="metric-questions">—</b><span>Questions awaiting review</span></div></div><section id="memberships" class="panel"><h2>Memberships &amp; learners</h2><p><small>The latest 500 membership and enrollment records from your site. For all registered accounts, use Clerk. Subscription status updates when Stripe events arrive or members refresh their accounts.</small></p><div id="dashboard-records">Loading your records…</div><a class="button" href="https://dashboard.clerk.com/" target="_blank" rel="noopener noreferrer">Open Clerk users ↗</a><a class="button" href="https://dashboard.stripe.com/" target="_blank" rel="noopener noreferrer">Open Stripe billing ↗</a></section>`;
 return html.slice(0,start)+shell+content+'</main></div>'+html.slice(bodyEnd+7);
}
