(async()=>{
 const el=id=>document.getElementById(id),show=text=>el('message').textContent=text;
 let currentVideo='',api,owner=false,checkout=null;
 async function script(src,key){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.crossOrigin='anonymous';if(key)s.dataset.clerkPublishableKey=key;s.onload=resolve;s.onerror=reject;document.head.append(s);});}
 function renderSettings(s){
  el('live-status').textContent=s?.is_live?'🔴 Live now':'Next Math Help Live';
  el('next-time').textContent=s?.starts_at?new Date(s.starts_at*1000).toLocaleString():'The next session time will be posted here.';
  if(currentVideo!==(s?.video_id||'')){currentVideo=s?.video_id||'';el('video').replaceChildren();if(currentVideo){const f=document.createElement('iframe');f.src='https://www.youtube-nocookie.com/embed/'+encodeURIComponent(currentVideo);f.title='Math Help Live';f.allow='autoplay; encrypted-media; picture-in-picture';f.allowFullscreen=true;el('video').append(f);}}
  el('chat-send').disabled=!s?.is_live;
 }
 function item(container,text){const p=document.createElement('div');p.className='item';p.textContent=text;container.append(p);return p;}
 async function publicStatus(){const r=await fetch('/api/live/public');if(r.ok)renderSettings((await r.json()).settings);else el('live-status').textContent='Live lessons are being set up.';}
 async function liveStatus(){const d=await api('/api/live/status');owner=d.owner;renderSettings(d.settings);el('members').hidden=false;el('instructor').hidden=!owner;el('questions-title').textContent=owner?'Learner question queue':'Your submitted questions';el('questions').replaceChildren();for(const q of d.questions){const p=item(el('questions'),(q.kind==='chat'?'Live question':'Advance question')+' · '+new Date(q.created_at*1000).toLocaleString()+'\n'+q.body);if(owner){const b=document.createElement('button');b.textContent='Mark handled / remove';b.onclick=async()=>{try{await api('/api/live/remove',{id:q.id});await liveStatus();}catch(e){show(e.message);}};p.append(b);}}if(owner&&!el('live-settings').contains(document.activeElement)){el('video-id').value=d.settings?.video_id||'';el('is-live').checked=!!d.settings?.is_live;const date=d.settings?.starts_at?new Date(d.settings.starts_at*1000):null;el('live-time').value=date?new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16):'';}}
 async function tutoringStatus(){const d=await api('/api/tutoring/status');el('tutoring-price').textContent='$'+(d.amount/100).toFixed(2)+' / one hour';el('slots').replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=d.slots.length?'Choose an hour':'No appointments published yet';el('slots').append(placeholder);for(const s of d.slots){const o=document.createElement('option');o.value=s.id;o.textContent=new Date(s.starts_at*1000).toLocaleString();el('slots').append(o);}el('book').disabled=!d.slots.length;el('bookings-title').textContent=d.owner?'All tutoring bookings':'Your appointments';el('bookings').replaceChildren();for(const b of d.bookings){const p=item(el('bookings'),new Date(b.starts_at*1000).toLocaleString()+' · '+(b.state==='paid'?'Payment received':b.state)+' · $'+(b.amount/100).toFixed(2)+'\n'+b.topic+(d.owner?'\nContact: '+(b.contact_email||'Awaiting payment'):''));if(b.lesson_url){const a=document.createElement('a');a.href=b.lesson_url;a.textContent='Open private lesson';a.className='button';a.target='_blank';a.rel='noopener noreferrer';p.append(a);}if(d.owner&&b.state==='paid'){const button=document.createElement('button');button.textContent='Set private lesson link';button.onclick=async()=>{const url=prompt('HTTPS link for this private lesson',b.lesson_url||'');if(!url)return;try{await api('/api/tutoring/details',{id:b.id,url});await tutoringStatus();}catch(e){show(e.message);}};p.append(button);}}}
 try{
  await publicStatus();
  const config=await(await fetch('/api/config')).json();
  if(!config.configured){show('Registration is being set up.');return;}
  const domain=atob(config.publishableKey.split('_')[2]).replace(/\$$/,'');
  await script(`https://${domain}/npm/@clerk/ui@1/dist/ui.browser.js`);
  await script(`https://${domain}/npm/@clerk/clerk-js@6/dist/clerk.browser.js`,config.publishableKey);
  await window.Clerk.load({ui:{ClerkUI:window.__internal_ClerkUICtor}});
  const clerk=window.Clerk;
  if(!clerk.isSignedIn){show('Sign in with an active membership or teacher class account to submit questions and book tutoring.');clerk.mountSignIn(el('auth'),{routing:'hash',forceRedirectUrl:'/live',signUpForceRedirectUrl:'/live'});setInterval(()=>publicStatus().catch(()=>{}),30000);return;}
  api=async(path,data={})=>{const token=await clerk.session.getToken();const r=await fetch(path,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw Error(b.error||'Please try again.');return b;};
  await liveStatus();await tutoringStatus();
  for(const kind of ['advance','chat'])el(kind+'-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await api('/api/live/question',{kind,body:el(kind+'-body').value});el(kind+'-body').value='';await liveStatus();show('Question submitted. I’ll review it for the lesson.');}catch(error){show(error.message);}finally{b.disabled=false;if(kind==='chat')await publicStatus();}};
  el('live-settings').onsubmit=async e=>{e.preventDefault();try{await api('/api/live/settings',{videoId:el('video-id').value.trim(),isLive:el('is-live').checked,startsAt:el('live-time').value?Math.floor(new Date(el('live-time').value).getTime()/1000):null});await liveStatus();show('Live lesson updated.');}catch(error){show(error.message);}};
  el('slot-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/tutoring/slot',{startsAt:Math.floor(new Date(el('slot-time').value).getTime()/1000)});await tutoringStatus();show('Tutoring hour published.');}catch(error){show(error.message);}};
  async function close(){if(checkout){checkout.destroy();checkout=null;}el('tutoring-checkout').hidden=true;el('booking-form').hidden=false;el('checkout-container').replaceChildren();}
  el('checkout-back').onclick=async()=>{await close();await tutoringStatus().catch(e=>show(e.message));};
  el('booking-form').onsubmit=async e=>{e.preventDefault();el('book').disabled=true;try{const d=await api('/api/tutoring/checkout',{slotId:el('slots').value,topic:el('tutoring-topic').value});if(!window.Stripe)await script('https://js.stripe.com/clover/stripe.js');await close();el('tutoring-checkout').hidden=false;el('booking-form').hidden=true;checkout=await window.Stripe(config.stripePublishableKey).createEmbeddedCheckoutPage({fetchClientSecret:async()=>d.clientSecret,onComplete:async()=>{await close();await tutoringStatus().catch(e=>show(e.message));show('Checking payment. Your confirmed appointment will appear above.');}});checkout.mount('#checkout-container');}catch(error){await close();show(error.message);}finally{el('book').disabled=false;}};
  setInterval(()=>liveStatus().catch(e=>show(e.message)),15000);
 }catch(e){show(e.message||'We could not load the lesson. Please refresh.');}
})();
